# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  myproject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passord123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    image: myproject
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    volumes:  
      - ../.certificates:/https/ 
    ports:
      - 8000:80
      - 8001:443
    networks:
      - home-network     

networks:
    home-network:
      driver: bridge    