FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["AzureKeyVaultConfig.csproj", "./"]
RUN dotnet restore "AzureKeyVaultConfig.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "AzureKeyVaultConfig.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "AzureKeyVaultConfig.csproj" -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AzureKeyVaultConfig.dll"]

